name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11  # Java 11 requis pour SonarQube
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
