name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted  # Utilise un runner auto-hébergé (votre machine Windows 11)
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Désactive les clones peu profonds pour une analyse plus pertinente

      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: sqp_ee4efd704e0e650fdc99fd2202ef1da924d95957
          SONAR_HOST_URL: "http://localhost:9000"  # Adresse locale du serveur SonarQube
        with:
          args: '-X'  # Ajoute l'option pour le mode débogage

      # Décommentez les lignes suivantes si vous souhaitez échouer le job en cas d'échec de la Quality Gate
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
